name: CI

on:
- push
- pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository.
    - uses: actions/checkout@v2

    # Install latest CMake and Ninja.
    - uses: lukka/get-cmake@latest

    # Install the APT requirements.
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev
        version: 1.0

    # Build the project.
    - name: Build
      run: cargo build --verbose
